services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_ENV=development
